# Name: Thiago de Oliveira da Costa StId: 2020005

### GitHub: https://github.com/ThBrasilDaCosta/CA2-ML-Neural-Semantic

### Project: ML - Neural Networks & Semantic Analysis

##### Importing necessary start libraries:

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#### Loading CSV file:

In [2]:
bank_records = pd.read_csv('BankRecords.csv')

#### Data Understanding:

In [3]:
bank_records.shape

(5000, 14)

In [4]:
bank_records.dtypes

ID                         int64
Age                        int64
Experience(Years)          int64
Income(Thousands's)        int64
Sort Code                  int64
Family                     int64
Credit Score             float64
Education                 object
Mortgage(Thousands's)      int64
Personal Loan             object
Securities Account        object
CD Account                object
Online Banking            object
CreditCard                object
dtype: object

In [5]:
bank_records.describe()

ID          Age  Experience(Years)  Income(Thousands's)  \
count  5000.000000  5000.000000        5000.000000          5000.000000   
mean   2500.500000    45.338400          20.104600            73.774200   
std    1443.520003    11.463166          11.467954            46.033729   
min       1.000000    23.000000          -3.000000             8.000000   
25%    1250.750000    35.000000          10.000000            39.000000   
50%    2500.500000    45.000000          20.000000            64.000000   
75%    3750.250000    55.000000          30.000000            98.000000   
max    5000.000000    67.000000          43.000000           224.000000   

          Sort Code       Family  Credit Score  Mortgage(Thousands's)  
count   5000.000000  5000.000000   5000.000000            5000.000000  
mean   93152.503000     2.396400      1.937913              56.498800  
std     2121.852197     1.147663      1.747666             101.713802  
min     9307.000000     1.000000      0.000000               0.000000  
25%    91911.000000     1.000000      0.700000               0.000000  
50%    93437.000000     2.000000      1.500000               0.000000  
75%    94608.000000     3.000000      2.500000             101.000000  
max    96651.000000     4.000000     10.000000             635.000000

In [6]:
bank_records.head()

ID  Age  Experience(Years)  Income(Thousands's)  Sort Code  Family  \
0   1   25                  1                   49      91107       4   
1   2   45                 19                   34      90089       3   
2   3   39                 15                   11      94720       1   
3   4   35                  9                  100      94112       1   
4   5   35                  8                   45      91330       4   

   Credit Score Education  Mortgage(Thousands's) Personal Loan  \
0           1.6   Diploma                      0            No   
1           1.5   Diploma                      0            No   
2           1.0   Diploma                      0            No   
3           2.7    Degree                      0            No   
4           1.0    Degree                      0            No   

  Securities Account CD Account Online Banking CreditCard  
0                Yes         No             No         No  
1                Yes         No             No         No  
2                 No         No             No         No  
3                 No         No             No         No  
4                 No         No             No        Yes

In [7]:
bank_records.isna().sum()

ID                       0
Age                      0
Experience(Years)        0
Income(Thousands's)      0
Sort Code                0
Family                   0
Credit Score             0
Education                0
Mortgage(Thousands's)    0
Personal Loan            0
Securities Account       0
CD Account               0
Online Banking           0
CreditCard               0
dtype: int64

In [8]:
bank_records.loc[bank_records.duplicated()]

Empty DataFrame
Columns: [ID, Age, Experience(Years), Income(Thousands's), Sort Code, Family, Credit Score, Education, Mortgage(Thousands's), Personal Loan, Securities Account, CD Account, Online Banking, CreditCard]
Index: []

In [9]:
bank_records.columns

Index(['ID', 'Age', 'Experience(Years)', 'Income(Thousands's)', 'Sort Code',
       'Family', 'Credit Score', 'Education', 'Mortgage(Thousands's)',
       'Personal Loan', 'Securities Account', 'CD Account', 'Online Banking',
       'CreditCard'],
      dtype='object')

#### Data Transformation / Feature Engineering:

In [10]:
bank_records = bank_records.rename(columns={"Income(Thousands's)": "Income(Thousands)", "Mortgage(Thousands's)":"Mortgage(Thousands)"})

In [11]:
bank_records.columns

Index(['ID', 'Age', 'Experience(Years)', 'Income(Thousands)', 'Sort Code',
       'Family', 'Credit Score', 'Education', 'Mortgage(Thousands)',
       'Personal Loan', 'Securities Account', 'CD Account', 'Online Banking',
       'CreditCard'],
      dtype='object')

In [12]:
bank_records = bank_records.drop(['ID', 'Sort Code',
       'Family', 'Credit Score','Mortgage(Thousands)',
       'Personal Loan', 'Securities Account', 'CD Account', 'Online Banking',
       'CreditCard'], axis = 1).copy()

In [13]:
bank_records

Age  Experience(Years)  Income(Thousands) Education
0      25                  1                 49   Diploma
1      45                 19                 34   Diploma
2      39                 15                 11   Diploma
3      35                  9                100    Degree
4      35                  8                 45    Degree
...   ...                ...                ...       ...
4995   29                  3                 40   Masters
4996   30                  4                 15   Diploma
4997   63                 39                 24   Masters
4998   65                 40                 49    Degree
4999   28                  4                 83   Diploma

[5000 rows x 4 columns]

In [14]:
bank_records['Education'].unique()

array(['Diploma', 'Degree', 'Masters'], dtype=object)

In [15]:
oe = ['Diploma', 'Degree', 'Masters']

In [16]:
from sklearn.preprocessing import OrdinalEncoder

In [17]:
oenc = OrdinalEncoder(categories = [oe])

In [18]:
bank_records['Education'] = oenc.fit_transform(bank_records[['Education']])

In [19]:
bank_records

Age  Experience(Years)  Income(Thousands)  Education
0      25                  1                 49        0.0
1      45                 19                 34        0.0
2      39                 15                 11        0.0
3      35                  9                100        1.0
4      35                  8                 45        1.0
...   ...                ...                ...        ...
4995   29                  3                 40        2.0
4996   30                  4                 15        0.0
4997   63                 39                 24        2.0
4998   65                 40                 49        1.0
4999   28                  4                 83        0.0

[5000 rows x 4 columns]

In [20]:
bank_records['Age'].unique()

array([25, 45, 39, 35, 37, 53, 50, 34, 65, 29, 48, 59, 67, 60, 38, 42, 46,
       55, 56, 57, 44, 36, 43, 40, 30, 31, 51, 32, 61, 41, 28, 49, 47, 62,
       58, 54, 33, 27, 66, 24, 52, 26, 64, 63, 23], dtype=int64)

In [21]:
bank_records['Experience(Years)'].unique()

array([ 1, 19, 15,  9,  8, 13, 27, 24, 10, 39,  5, 23, 32, 41, 30, 14, 18,
       21, 28, 31, 11, 16, 20, 35,  6, 25,  7, 12, 26, 37, 17,  2, 36, 29,
        3, 22, -1, 34,  0, 38, 40, 33,  4, -2, 42, -3, 43], dtype=int64)

In [22]:
bank_records['Experience(Years)'] = bank_records['Experience(Years)'].abs()

In [23]:
bank_records['Experience(Years)'].unique()

array([ 1, 19, 15,  9,  8, 13, 27, 24, 10, 39,  5, 23, 32, 41, 30, 14, 18,
       21, 28, 31, 11, 16, 20, 35,  6, 25,  7, 12, 26, 37, 17,  2, 36, 29,
        3, 22, 34,  0, 38, 40, 33,  4, 42, 43], dtype=int64)

In [24]:
bank_records['Income(Thousands)'].unique()

array([ 49,  34,  11, 100,  45,  29,  72,  22,  81, 180, 105, 114,  40,
       112, 130, 193,  21,  25,  63,  62,  43, 152,  83, 158,  48, 119,
        35,  41,  18,  50, 121,  71, 141,  80,  84,  60, 132, 104,  52,
       194,   8, 131, 190,  44, 139,  93, 188,  39, 125,  32,  20, 115,
        69,  85, 135,  12, 133,  19,  82, 109,  42,  78,  51, 113, 118,
        64, 161,  94,  15,  74,  30,  38,   9,  92,  61,  73,  70, 149,
        98, 128,  31,  58,  54, 124, 163,  24,  79, 134,  23,  13, 138,
       171, 168,  65,  10, 148, 159, 169, 144, 165,  59,  68,  91, 172,
        55, 155,  53,  89,  28,  75, 170, 120,  99, 111,  33, 129, 122,
       150, 195, 110, 101, 191, 140, 153, 173, 174,  90, 179, 145, 200,
       183, 182,  88, 160, 205, 164,  14, 175, 103, 108, 185, 204, 154,
       102, 192, 202, 162, 142,  95, 184, 181, 143, 123, 178, 198, 201,
       203, 189, 151, 199, 224, 218], dtype=int64)

In [25]:
bank_records['Education'].unique()

array([0., 1., 2.])

#### Splitting Dataset / Modelling:

##### Splitting:

In [26]:
indpt_feat = bank_records.drop('Income(Thousands)', axis = 'columns')
dpt_feat = bank_records['Income(Thousands)']

X = indpt_feat
y = dpt_feat

In [27]:
X

Age  Experience(Years)  Education
0      25                  1        0.0
1      45                 19        0.0
2      39                 15        0.0
3      35                  9        1.0
4      35                  8        1.0
...   ...                ...        ...
4995   29                  3        2.0
4996   30                  4        0.0
4997   63                 39        2.0
4998   65                 40        1.0
4999   28                  4        0.0

[5000 rows x 3 columns]

In [28]:
y

0        49
1        34
2        11
3       100
4        45
       ... 
4995     40
4996     15
4997     24
4998     49
4999     83
Name: Income(Thousands), Length: 5000, dtype: int64

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=17, test_size=0.2)

In [31]:
X_train.shape

(4000, 3)

In [32]:
X_test.shape

(1000, 3)

In [33]:
y_train.shape

(4000,)

In [34]:
y_test.shape

(1000,)

##### Modelling:

In [38]:
X_train

Age  Experience(Years)  Education
1926   30                  6        1.0
805    55                 29        1.0
1674   37                 11        1.0
81     47                 22        1.0
2266   38                 13        0.0
...   ...                ...        ...
2800   52                 26        1.0
1337   26                  0        1.0
406    45                 19        0.0
2191   42                 18        0.0
2671   62                 37        0.0

[4000 rows x 3 columns]

In [39]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [40]:
model = Sequential()
model.add(Dense(64, activation= 'relu', input_shape=(X_train.shape[1],)))
model.add(Dense(32, activation= 'relu'))
model.add(Dense(1))

model.compile(optimizer='adam', loss='mse', metrics=['mae'])

early_stopping = EarlyStopping(patience=5)

model.fit(X_train, y_train, validation_split=0.2, epochs=100, batch_size=32, verbose=2, callbacks = [early_stopping])

loss, mae = model.evaluate(X_test, y_test, verbose=2)

Epoch 1/100


C:\Users\thiag\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


100/100 - 2s - 16ms/step - loss: 3669.0735 - mae: 46.3784 - val_loss: 2431.8223 - val_mae: 38.2349
Epoch 2/100
100/100 - 0s - 2ms/step - loss: 2573.2859 - mae: 39.9974 - val_loss: 2266.2041 - val_mae: 37.0958
Epoch 3/100
100/100 - 0s - 2ms/step - loss: 2402.9355 - mae: 38.8875 - val_loss: 2191.4121 - val_mae: 37.8411
Epoch 4/100
100/100 - 0s - 2ms/step - loss: 2270.7732 - mae: 38.2174 - val_loss: 2044.3448 - val_mae: 36.0815
Epoch 5/100
100/100 - 0s - 2ms/step - loss: 2197.4104 - mae: 37.6963 - val_loss: 2022.7450 - val_mae: 36.2459
Epoch 6/100
100/100 - 0s - 2ms/step - loss: 2165.0125 - mae: 37.5481 - val_loss: 2001.2965 - val_mae: 35.5912
Epoch 7/100
100/100 - 0s - 2ms/step - loss: 2145.6816 - mae: 37.3081 - val_loss: 1992.9111 - val_mae: 35.6006
Epoch 8/100
100/100 - 0s - 2ms/step - loss: 2138.1633 - mae: 37.3312 - val_loss: 2002.7819 - val_mae: 36.2453
Epoch 9/100
100/100 - 0s - 2ms/step - loss: 2134.0664 - mae: 37.2073 - val_loss: 1977.2155 - val_mae: 35.5339
Epoch 10/100
100/100 

In [41]:
print(f"Mean Squared Error: {loss}")
print(f"Mean Absolute Error: {mae}")

Mean Squared Error: 2044.7432861328125
Mean Absolute Error: 36.25133514404297


In [42]:

input_feat = np.array([[30, 5, 2.0]])
predicted_income = model.predict(input_feat.reshape(1,3), batch_size=1)
print(predicted_income)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
[[63.1484]]


In [43]:
y_pred = model.predict(X_test)*1000

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step 


In [44]:
y_pred

array([[57073.324],
       [71862.97 ],
       [65239.016],
       [61731.36 ],
       [90803.93 ],
       [91789.61 ],
       [85769.37 ],
       [71862.97 ],
       [63012.14 ],
       [60185.793],
       [77158.2  ],
       [72045.35 ],
       [75700.5  ],
       [61731.36 ],
       [66613.86 ],
       [59620.703],
       [78655.82 ],
       [68769.53 ],
       [78740.8  ],
       [84284.1  ],
       [70239.39 ],
       [73244.66 ],
       [74729.93 ],
       [69592.73 ],
       [64773.5  ],
       [72045.35 ],
       [77302.69 ],
       [60919.81 ],
       [63646.574],
       [85769.37 ],
       [82139.72 ],
       [78740.8  ],
       [70092.69 ],
       [77300.11 ],
       [70176.805],
       [73759.02 ],
       [70671.89 ],
       [70122.5  ],
       [75171.94 ],
       [56396.754],
       [89375.625],
       [73935.03 ],
       [63264.277],
       [80415.82 ],
       [83829.46 ],
       [81277.766],
       [79027.805],
       [60030.805],
       [74179.33 ],
       [86705.93 ],


##### Model Tuning

In [45]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [ ]:
param_grid = {
    'neurons': [16, 32, 64],
    'activation': ['relu', 'tanh'],
    'optimizer': ['adam', 'rmsprop'],
    'batch_size': [16, 32, 64],
    'e'
}